# Generated by Django 2.2.24 on 2021-09-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('aliases', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('aromas', models.ManyToManyField(related_name='strain_aromas', to='mary.Aroma')),
                ('effects', models.ManyToManyField(related_name='strain_effects', to='mary.Effect')),
                ('terpenes', models.ManyToManyField(related_name='strain_terpenes', to='mary.Terpene')),
            ],
        ),
    ]
